version 0.2

phase:
      install:
              runtime-versions:
                      php: 7.3
              commands:
                  - echo pre build
      pre_build:
              commands:
                  - echo prebuild
      build:
              commands:
                  - echo build
      post_build:
              commands:
                  - echo post build
artifacts:
        files:
             - '**/*'
